### ISSUE TITLE
Incorrect release version is used in PyPI upload when fix release updated

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-index-data#18]
Instead of 17.0.1 the workflow is using 17.0.0 somehow!

https://github.com/ImagingDataCommons/idc-index-data/actions/runs/8609215231/job/23592839431

<img width="1037" alt="image" src="https://github.com/ImagingDataCommons/idc-index-data/assets/313942/81cb5abf-a117-4671-8b41-842bbce76e34">

**Comment by fedorov** [comment]
It worked, thank you @vkt1414!

It would be nice to figure out how to publish without changing that line, if possible. If we can publish without manually writing release into that file with `idc-index`, is there a reason why it is not possible in this package?

**Comment by vkt1414** [comment]
It was done to ensure reproducibility if one wants to install from the source.

I'm afraid we are also not building on JC's work here.

https://github.com/ImagingDataCommons/idc-index-data/blob/main/scripts/python/update_idc_index_version.py
